# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'zhCN.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(309, 495)
        font = QFont()
        font.setFamilies([u"Arial"])
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"../../images/pride.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.import_settings = QAction(MainWindow)
        self.import_settings.setObjectName(u"import_settings")
        self.exit = QAction(MainWindow)
        self.exit.setObjectName(u"exit")
        self.choose_language_profile = QAction(MainWindow)
        self.choose_language_profile.setObjectName(u"choose_language_profile")
        self.about = QAction(MainWindow)
        self.about.setObjectName(u"about")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.main_title = QLabel(self.centralwidget)
        self.main_title.setObjectName(u"main_title")
        self.main_title.setGeometry(QRect(0, 0, 311, 61))
        font1 = QFont()
        font1.setFamilies([u"STXihei"])
        font1.setPointSize(20)
        self.main_title.setFont(font1)
        self.main_title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.news = QLabel(self.centralwidget)
        self.news.setObjectName(u"news")
        self.news.setGeometry(QRect(180, 0, 131, 21))
        font2 = QFont()
        font2.setFamilies([u"\u534e\u6587\u7ec6\u9ed1"])
        font2.setPointSize(12)
        self.news.setFont(font2)
        self.news.setTextFormat(Qt.TextFormat.AutoText)
        self.news.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTop|Qt.AlignmentFlag.AlignTrailing)
        self.tabs = QTabWidget(self.centralwidget)
        self.tabs.setObjectName(u"tabs")
        self.tabs.setGeometry(QRect(0, 50, 311, 421))
        self.common_use = QWidget()
        self.common_use.setObjectName(u"common_use")
        self.translator = QPushButton(self.common_use)
        self.translator.setObjectName(u"translator")
        self.translator.setGeometry(QRect(10, 10, 131, 41))
        self.weather_report = QPushButton(self.common_use)
        self.weather_report.setObjectName(u"weather_report")
        self.weather_report.setGeometry(QRect(170, 10, 131, 41))
        self.speech_to_text = QPushButton(self.common_use)
        self.speech_to_text.setObjectName(u"speech_to_text")
        self.speech_to_text.setGeometry(QRect(10, 60, 131, 41))
        self.easy_to_do = QPushButton(self.common_use)
        self.easy_to_do.setObjectName(u"easy_to_do")
        self.easy_to_do.setGeometry(QRect(170, 60, 131, 41))
        self.password_creator = QPushButton(self.common_use)
        self.password_creator.setObjectName(u"password_creator")
        self.password_creator.setGeometry(QRect(10, 110, 131, 41))
        self.tabs.addTab(self.common_use, "")
        self.other_tools = QWidget()
        self.other_tools.setObjectName(u"other_tools")
        self.calculator = QPushButton(self.other_tools)
        self.calculator.setObjectName(u"calculator")
        self.calculator.setGeometry(QRect(10, 10, 121, 31))
        self.hash_checker = QPushButton(self.other_tools)
        self.hash_checker.setObjectName(u"hash_checker")
        self.hash_checker.setGeometry(QRect(10, 50, 121, 31))
        self.licence_creator = QPushButton(self.other_tools)
        self.licence_creator.setObjectName(u"licence_creator")
        self.licence_creator.setGeometry(QRect(10, 90, 121, 31))
        self.send_mail_from_json = QPushButton(self.other_tools)
        self.send_mail_from_json.setObjectName(u"send_mail_from_json")
        self.send_mail_from_json.setGeometry(QRect(10, 130, 121, 31))
        self.ip_group = QGroupBox(self.other_tools)
        self.ip_group.setObjectName(u"ip_group")
        self.ip_group.setGeometry(QRect(10, 170, 121, 131))
        self.get_ip = QPushButton(self.ip_group)
        self.get_ip.setObjectName(u"get_ip")
        self.get_ip.setGeometry(QRect(10, 50, 101, 31))
        self.get_doamin = QPushButton(self.ip_group)
        self.get_doamin.setObjectName(u"get_doamin")
        self.get_doamin.setGeometry(QRect(10, 90, 101, 31))
        self.qrcode_group = QGroupBox(self.other_tools)
        self.qrcode_group.setObjectName(u"qrcode_group")
        self.qrcode_group.setGeometry(QRect(150, 250, 141, 131))
        self.create_qr = QPushButton(self.qrcode_group)
        self.create_qr.setObjectName(u"create_qr")
        self.create_qr.setGeometry(QRect(10, 50, 121, 31))
        self.reslove_qr = QPushButton(self.qrcode_group)
        self.reslove_qr.setObjectName(u"reslove_qr")
        self.reslove_qr.setGeometry(QRect(10, 90, 121, 31))
        self.file_group = QGroupBox(self.other_tools)
        self.file_group.setObjectName(u"file_group")
        self.file_group.setGeometry(QRect(150, 10, 141, 221))
        self.json_to_csv = QPushButton(self.file_group)
        self.json_to_csv.setObjectName(u"json_to_csv")
        self.json_to_csv.setGeometry(QRect(10, 50, 121, 31))
        self.csv_to_json = QPushButton(self.file_group)
        self.csv_to_json.setObjectName(u"csv_to_json")
        self.csv_to_json.setGeometry(QRect(10, 90, 121, 31))
        self.json_to_xml = QPushButton(self.file_group)
        self.json_to_xml.setObjectName(u"json_to_xml")
        self.json_to_xml.setGeometry(QRect(10, 140, 121, 31))
        self.xml_to_json = QPushButton(self.file_group)
        self.xml_to_json.setObjectName(u"xml_to_json")
        self.xml_to_json.setGeometry(QRect(10, 180, 121, 31))
        self.tabs.addTab(self.other_tools, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 309, 20))
        self.file_menu = QMenu(self.menubar)
        self.file_menu.setObjectName(u"file_menu")
        self.settings_menu = QMenu(self.menubar)
        self.settings_menu.setObjectName(u"settings_menu")
        self.help_menu = QMenu(self.menubar)
        self.help_menu.setObjectName(u"help_menu")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.settings_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())
        self.file_menu.addAction(self.import_settings)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit)
        self.settings_menu.addAction(self.choose_language_profile)
        self.help_menu.addAction(self.about)

        self.retranslateUi(MainWindow)

        self.tabs.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Windows Utilities", None))
        self.import_settings.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u8bbe\u7f6e", None))
        self.exit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.choose_language_profile.setText(QCoreApplication.translate("MainWindow", u"Choose Language Profile...", None))
        self.about.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.main_title.setText(QCoreApplication.translate("MainWindow", u"Windows Utilities", None))
        self.news.setText(QCoreApplication.translate("MainWindow", u"\u65b0Qt\u67b6\u6784\u51fa\u573a\uff01", None))
        self.translator.setText(QCoreApplication.translate("MainWindow", u"\u7ffb\u8bd1\u5668", None))
        self.weather_report.setText(QCoreApplication.translate("MainWindow", u"\u5929\u6c14\u9884\u62a5", None))
        self.speech_to_text.setText(QCoreApplication.translate("MainWindow", u"\u8bed\u97f3\u8f6c\u6587\u5b57", None))
        self.easy_to_do.setText(QCoreApplication.translate("MainWindow", u"Easy To Do", None))
        self.password_creator.setText(QCoreApplication.translate("MainWindow", u"\u5bc6\u7801\u751f\u6210\u5668", None))
        self.tabs.setTabText(self.tabs.indexOf(self.common_use), QCoreApplication.translate("MainWindow", u"\u5e38\u7528\u5de5\u5177", None))
        self.calculator.setText(QCoreApplication.translate("MainWindow", u"\u8ba1\u7b97\u5668", None))
        self.hash_checker.setText(QCoreApplication.translate("MainWindow", u"\u6821\u9a8c\u54c8\u5e0c", None))
        self.licence_creator.setText(QCoreApplication.translate("MainWindow", u"\u8bb8\u53ef\u8bc1\u521b\u9020\u5668", None))
        self.send_mail_from_json.setText(QCoreApplication.translate("MainWindow", u"\u6279\u91cf\u53d1\u9001\u90ae\u4ef6", None))
        self.ip_group.setTitle(QCoreApplication.translate("MainWindow", u"IP \u5de5\u5177", None))
        self.get_ip.setText(QCoreApplication.translate("MainWindow", u"\u83b7\u53d6IP", None))
        self.get_doamin.setText(QCoreApplication.translate("MainWindow", u"\u83b7\u53d6\u57df\u540d", None))
        self.qrcode_group.setTitle(QCoreApplication.translate("MainWindow", u"\u4e8c\u7ef4\u7801\u5de5\u5177", None))
        self.create_qr.setText(QCoreApplication.translate("MainWindow", u"\u751f\u6210\u4e8c\u7ef4\u7801", None))
        self.reslove_qr.setText(QCoreApplication.translate("MainWindow", u"\u89e3\u6790\u4e8c\u7ef4\u7801", None))
        self.file_group.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6\u5de5\u5177", None))
        self.json_to_csv.setText(QCoreApplication.translate("MainWindow", u"JSON \u8f6c CSV", None))
        self.csv_to_json.setText(QCoreApplication.translate("MainWindow", u"CSV \u8f6c JSON", None))
        self.json_to_xml.setText(QCoreApplication.translate("MainWindow", u"JSON \u8f6c XML", None))
        self.xml_to_json.setText(QCoreApplication.translate("MainWindow", u"XML \u8f6c JSON", None))
        self.tabs.setTabText(self.tabs.indexOf(self.other_tools), QCoreApplication.translate("MainWindow", u"\u5176\u4ed6\u5de5\u5177", None))
        self.file_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.settings_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.help_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
    # retranslateUi

