# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'calc.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLCDNumber, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(311, 406)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.result = QLCDNumber(self.centralwidget)
        self.result.setObjectName(u"result")
        self.result.setGeometry(QRect(0, 0, 301, 91))
        self.numbers = QGroupBox(self.centralwidget)
        self.numbers.setObjectName(u"numbers")
        self.numbers.setGeometry(QRect(10, 180, 161, 221))
        self.button_1 = QPushButton(self.numbers)
        self.button_1.setObjectName(u"button_1")
        self.button_1.setGeometry(QRect(10, 20, 41, 41))
        self.button_2 = QPushButton(self.numbers)
        self.button_2.setObjectName(u"button_2")
        self.button_2.setGeometry(QRect(60, 20, 41, 41))
        self.button_3 = QPushButton(self.numbers)
        self.button_3.setObjectName(u"button_3")
        self.button_3.setGeometry(QRect(110, 20, 41, 41))
        self.button_4 = QPushButton(self.numbers)
        self.button_4.setObjectName(u"button_4")
        self.button_4.setGeometry(QRect(10, 70, 41, 41))
        self.button_5 = QPushButton(self.numbers)
        self.button_5.setObjectName(u"button_5")
        self.button_5.setGeometry(QRect(60, 70, 41, 41))
        self.button_6 = QPushButton(self.numbers)
        self.button_6.setObjectName(u"button_6")
        self.button_6.setGeometry(QRect(110, 70, 41, 41))
        self.button_7 = QPushButton(self.numbers)
        self.button_7.setObjectName(u"button_7")
        self.button_7.setGeometry(QRect(10, 120, 41, 41))
        self.button_8 = QPushButton(self.numbers)
        self.button_8.setObjectName(u"button_8")
        self.button_8.setGeometry(QRect(60, 120, 41, 41))
        self.button_9 = QPushButton(self.numbers)
        self.button_9.setObjectName(u"button_9")
        self.button_9.setGeometry(QRect(110, 120, 41, 41))
        self.button_0 = QPushButton(self.numbers)
        self.button_0.setObjectName(u"button_0")
        self.button_0.setGeometry(QRect(60, 170, 41, 41))
        self.button_00 = QPushButton(self.numbers)
        self.button_00.setObjectName(u"button_00")
        self.button_00.setGeometry(QRect(110, 170, 41, 41))
        self.button_dot = QPushButton(self.numbers)
        self.button_dot.setObjectName(u"button_dot")
        self.button_dot.setGeometry(QRect(10, 170, 41, 41))
        self.functions = QGroupBox(self.centralwidget)
        self.functions.setObjectName(u"functions")
        self.functions.setGeometry(QRect(10, 100, 161, 71))
        self.button_ce = QPushButton(self.functions)
        self.button_ce.setObjectName(u"button_ce")
        self.button_ce.setGeometry(QRect(10, 20, 61, 41))
        self.button_c = QPushButton(self.functions)
        self.button_c.setObjectName(u"button_c")
        self.button_c.setGeometry(QRect(90, 20, 61, 41))
        self.signs = QGroupBox(self.centralwidget)
        self.signs.setObjectName(u"signs")
        self.signs.setGeometry(QRect(190, 100, 111, 301))
        self.button_add = QPushButton(self.signs)
        self.button_add.setObjectName(u"button_add")
        self.button_add.setGeometry(QRect(10, 20, 41, 41))
        self.button_sub = QPushButton(self.signs)
        self.button_sub.setObjectName(u"button_sub")
        self.button_sub.setGeometry(QRect(60, 20, 41, 41))
        self.button_mul = QPushButton(self.signs)
        self.button_mul.setObjectName(u"button_mul")
        self.button_mul.setGeometry(QRect(10, 70, 41, 41))
        self.button_div = QPushButton(self.signs)
        self.button_div.setObjectName(u"button_div")
        self.button_div.setGeometry(QRect(60, 70, 41, 41))
        self.button_equ = QPushButton(self.signs)
        self.button_equ.setObjectName(u"button_equ")
        self.button_equ.setGeometry(QRect(10, 220, 91, 71))
        self.button_per = QPushButton(self.signs)
        self.button_per.setObjectName(u"button_per")
        self.button_per.setGeometry(QRect(10, 120, 41, 41))
        self.button_pn = QPushButton(self.signs)
        self.button_pn.setObjectName(u"button_pn")
        self.button_pn.setGeometry(QRect(60, 120, 41, 41))
        self.button_clo = QPushButton(self.signs)
        self.button_clo.setObjectName(u"button_clo")
        self.button_clo.setGeometry(QRect(10, 170, 41, 41))
        self.button_root = QPushButton(self.signs)
        self.button_root.setObjectName(u"button_root")
        self.button_root.setGeometry(QRect(60, 170, 41, 41))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u8ba1\u7b97\u5668", None))
        self.numbers.setTitle(QCoreApplication.translate("MainWindow", u"\u6570\u5b57", None))
        self.button_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.button_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.button_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.button_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.button_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.button_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.button_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.button_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.button_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.button_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.button_00.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.button_dot.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.functions.setTitle(QCoreApplication.translate("MainWindow", u"\u529f\u80fd", None))
        self.button_ce.setText(QCoreApplication.translate("MainWindow", u"CE", None))
        self.button_c.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.signs.setTitle(QCoreApplication.translate("MainWindow", u"\u7b26\u53f7", None))
        self.button_add.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.button_sub.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.button_mul.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.button_div.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.button_equ.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.button_per.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.button_pn.setText(QCoreApplication.translate("MainWindow", u"\u00b1", None))
        self.button_clo.setText(QCoreApplication.translate("MainWindow", u"x^y", None))
        self.button_root.setText(QCoreApplication.translate("MainWindow", u"2\u221ax", None))
    # retranslateUi

